theme = "dracula"

[editor]
line-number = "absolute"
mouse = true
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
completion-trigger-len = 1
idle-timeout = 0
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
skip-levels = 1
character = "╎"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[keys.normal]
"C-s" = ":w"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
"C-w" = ":buffer-close"
"g" = { v = "jump_backward"}
space.g.b = ":sh git log -n 5 --pretty=format:'[%%h](%%cd %%cn): %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
space.g.g = "changed_file_picker"
space.q = ":q!"

[keys.insert]
"C-s" = ["normal_mode",":w"]
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
"C-w" = ":buffer-close"
