theme = "everforest_light"

[editor]
line-number = "absolute"
mouse = true
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
auto-completion = true
completion-trigger-len = 1
idle-timeout = 0
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
clipboard-provider = "termcode"


[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
skip-levels = 1
character = "╎"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[keys.normal]
"C-s" = ":w"
"C-q" = "jump_backward"
space.q = ":q"
"C-c" = ["yank_main_selection_to_clipboard"]
"C-v" = ["paste_clipboard_after"]
space.space = "file_picker"
space.b.d = ":bc"
space.b.o = ":bco"
space.f.f = "file_picker"
space.f.F = "file_picker_in_current_directory"
space.f.b = "buffer_picker"
space.s.s = "symbol_picker"
space.s.S = "workspace_symbol_picker"
space.s.b = "@<space>/ %p <C-r>%<C-a>"
space.s.g = [":clear-register","global_search"]
space.s.w = "@lbe*<space>/(?-i)<C-r>/"
space.s.W = "@lbe*<space>/(?-i)<C-r>/ %p <C-r>%"
tab = ":buffer-next"
S-tab = ":buffer-previous"
space.g.b = ":sh git log -n 5 --pretty=format:'[%%h](%%cd %%cn): %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
space.g.g = "changed_file_picker"

[keys.insert]
"C-s" = ["normal_mode",":w"]
"C-c" = ["yank_main_selection_to_clipboard"]
"C-v" = ["paste_clipboard_after"]

[keys.select]
"C-s" = ["normal_mode", ":w"]
"C-c" = ["yank_main_selection_to_clipboard"]
"C-v" = ["replace_selections_with_clipboard"]
