[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "cpp"
formatter = { command = "clang-format", args = ["-i", "--style=Google"] }

[[language]]
name = "c"
formatter = { command = "clang-format", args = ["-i"] }

[[language]]
name = "java"
formatter = { command = "google-java-format", args = ["-"] }
roots = ["pom.xml", "build.gradle", "build.gradle.kts", ".git", ".classpath"]

[language-server.jdtls]
command = "jdtls"
# 可以在 args 中配置数据持久化路径，防止每次重启都全量扫描
args = ["-data", "./.helix"]

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--edition", "2021"] }

# 定义 PlantUML 语言
[[language]]
name = "plantuml"
scope = "source.pu"
injection-regex = "puml|plantuml"
file-types = ["puml", "plantuml", "pu", "wsd"]
comment-token = "'"
indent = { tab-width = 2, unit = " " }

[[grammar]]
name = "plantuml"
source = { git = "https://github.com/Decodetalkers/tree_sitter_plantuml.git", rev = "gh-pages"}

